

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./static:/app/static
    networks:
      - bot-net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge


