"""Convert start_time and end_time to Time

Revision ID: 8ff4d4f7a78a
Revises: e24070057f34
Create Date: 2025-04-24 21:31:23.506596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff4d4f7a78a'
down_revision: Union[str, None] = 'e24070057f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('time_slots', 'start_time',
    #            existing_type=sa.VARCHAR(length=5),
    #            type_=sa.Time(),
    #            existing_nullable=False)
    # op.alter_column('time_slots', 'end_time',
    #            existing_type=sa.VARCHAR(length=5),
    #            type_=sa.Time(),
    #            existing_nullable=False)
    op.execute("ALTER TABLE time_slots ALTER COLUMN start_time TYPE TIME USING start_time::time")
    op.execute("ALTER TABLE time_slots ALTER COLUMN end_time TYPE TIME USING end_time::time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('time_slots', 'start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
